# Generated by Django 4.2.3 on 2024-01-22 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='العنوان')),
                ('description', models.CharField(max_length=200, verbose_name='الوصف')),
                ('due_date', models.DateField(verbose_name='فترة')),
                ('status', models.IntegerField(choices=[(1, 'Done'), (2, 'InProgress'), (3, 'ToDo')], verbose_name='الحالة')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='الاسم ')),
                ('last_name', models.CharField(max_length=50, verbose_name='اللقب')),
                ('number', models.IntegerField(verbose_name='الرقم')),
                ('email', models.EmailField(max_length=50, verbose_name='ايميل')),
                ('hire_date', models.DateField(verbose_name='تاريخ ')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.employeetask', verbose_name='نوع المهمة')),
            ],
        ),
    ]
