# Generated by Django 4.2.3 on 2024-01-13 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='النوع')),
                ('description', models.TextField(max_length=150, verbose_name='الوصف')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, verbose_name='الرقم')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accounttype')),
            ],
        ),
    ]
