# Generated by Django 4.2.3 on 2024-01-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounttype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='الوصف'),
        ),
    ]
