# Generated by Django 4.2.3 on 2024-01-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_accounttype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.IntegerField(choices=[(1, 'نشط'), (2, 'موقف')], default=1, verbose_name='الحالة'),
            preserve_default=False,
        ),
    ]
