# Generated by Django 4.2.3 on 2024-01-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_currency_transaction_remove_account_account_type_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='currency',
            table='Currency',
        ),
    ]
