# Generated by Django 4.2.3 on 2024-02-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_brand_brand_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.PositiveIntegerField(db_column='brand_id', primary_key=True, serialize=False),
        ),
    ]
